//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mktDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class mkCliCargo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mkCliCargo()
        {
            this.mkContacto = new HashSet<mkContacto>();
        }
    
        public int mkCliCargoId { get; set; }
        public Nullable<int> mkCliCategoriaId { get; set; }
        public string CliCargoValue { get; set; }
    
        public virtual mkCliCategoria mkCliCategoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mkContacto> mkContacto { get; set; }
    }
}
