//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mktDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class mkContacto
    {
        public int mkContactoId { get; set; }
        public Nullable<int> mkClienteId { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Cumpleanos { get; set; }
        public Nullable<int> mkCliCargoId { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
    
        public virtual mkCliCargo mkCliCargo { get; set; }
        public virtual mkCliente mkCliente { get; set; }
    }
}
