//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mktDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class mkMarca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mkMarca()
        {
            this.mkMarketingMarca = new HashSet<mkMarketingMarca>();
        }
    
        public int mkMarcaId { get; set; }
        public string mkMarcaValue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mkMarketingMarca> mkMarketingMarca { get; set; }
    }
}
