//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mktDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class mkMarketingSol
    {
        public int mkMarketingSolId { get; set; }
        public Nullable<int> mkSolucionId { get; set; }
        public Nullable<int> mkCliCategoriaId { get; set; }
        public string RecibeInfo { get; set; }
    
        public virtual mkCliCategoria mkCliCategoria { get; set; }
        public virtual mkSolucion mkSolucion { get; set; }
    }
}
