//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mktDB.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class mkSolucion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mkSolucion()
        {
            this.mkMarketingSol = new HashSet<mkMarketingSol>();
        }
    
        public int mkSolucionId { get; set; }
        public string mkSolucionValue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mkMarketingSol> mkMarketingSol { get; set; }
    }
}
