//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mktDB.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class mkUser
    {
        public int mkUserId { get; set; }
        public string User { get; set; }
        public string Passwd { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Rol { get; set; }
        public string isActive { get; set; }
    }
}
